version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123

    volumes:
      - data:/var/lib/postgresql/data  

  
  pg-admin:
    image: dpage/pgadmin

    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    
    ports:
      - "5050:5050"
   
volumes:
  data: 
      
    